[project]
name = "mvp-expense-approval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "loguru>=0.7.3",
    "pwdlib[argon2]>=0.3.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "pyjwt[crypto]>=2.13.0",
    "sqlalchemy[asyncio]>=2.0.52",
]

[dependency-groups]
dev = [
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.6",
]
