"""initial_schema

Revision ID: b0377c2e8e29
Revises: 
Create Date: 2026-09-06 21:04:31.639049

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b0377c2e8e29'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),

    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_revoked_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('category_approvers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('OFFICE', 'TRAVEL', 'CLIENT_ENTERTAINMENT', 'SOFTWARE_SUBSCRIPTIONS', 'OTHER', name='expensecategory', native_enum=False, length=50), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_approvers_approver_id'), 'category_approvers', ['approver_id'], unique=False)
    op.create_index(op.f('ix_category_approvers_category'), 'category_approvers', ['category'], unique=True)
    op.create_table('expenses',
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('OFFICE', 'TRAVEL', 'CLIENT_ENTERTAINMENT', 'SOFTWARE_SUBSCRIPTIONS', 'OTHER', name='expensecategory', native_enum=False, length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('payment_details', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', name='expensestatus', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_approver_id', sa.UUID(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_approver_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_applicant_id'), 'expenses', ['applicant_id'], unique=False)
    op.create_index('ix_expenses_applicant_status', 'expenses', ['applicant_id', 'status'], unique=False)
    op.create_index('ix_expenses_approver_status', 'expenses', ['assigned_approver_id', 'status'], unique=False)
    op.create_index(op.f('ix_expenses_assigned_approver_id'), 'expenses', ['assigned_approver_id'], unique=False)
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_table('approval_logs',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', 'WITHDRAW', name='approvalaction', native_enum=False, length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_logs_actor_id'), 'approval_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_approval_logs_expense_id'), 'approval_logs', ['expense_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_logs_expense_id'), table_name='approval_logs')
    op.drop_index(op.f('ix_approval_logs_actor_id'), table_name='approval_logs')
    op.drop_table('approval_logs')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_assigned_approver_id'), table_name='expenses')
    op.drop_index('ix_expenses_approver_status', table_name='expenses')
    op.drop_index('ix_expenses_applicant_status', table_name='expenses')
    op.drop_index(op.f('ix_expenses_applicant_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_category_approvers_category'), table_name='category_approvers')
    op.drop_index(op.f('ix_category_approvers_approver_id'), table_name='category_approvers')
    op.drop_table('category_approvers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
